"""
CUANIMUS Assisted Configuration Proposal Engine.
Allows AI agents to generate structured, auditable configuration proposals,
compute delta diffs, run pre-flight validation against invariants,
and present human-readable approval summaries without editing core source code.
"""
import copy
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Dict, Any, List, Optional, Tuple

from cuanimus.config.loader import ConfigLoader
from cuanimus.config.validator import ConfigValidator
from cuanimus.config.models import CuanimusConfig


class ProposalStatus(str, Enum):
    DRAFT = "DRAFT"
    VALID = "VALID"
    INVALID = "INVALID"
    REJECTED = "REJECTED"
    APPROVED = "APPROVED"
    APPLIED = "APPLIED"


@dataclass
class ConfigDelta:
    """Represents a single field difference between current and proposed config."""
    path: str
    old_value: Any
    new_value: Any
    impact_level: str  # SAFE, NOTICE, CRITICAL


@dataclass
class ConfigurationProposal:
    """
    Structured proposal generated by an AI Agent for human operator review.
    """
    proposal_id: str
    agent_id: str
    rationale: str
    current_config: Dict[str, Any]
    proposed_config: Dict[str, Any]
    deltas: List[ConfigDelta] = field(default_factory=list)
    validation_passed: bool = False
    validation_errors: List[str] = field(default_factory=list)
    validation_warnings: List[str] = field(default_factory=list)
    safety_status: str = "UNKNOWN"
    status: ProposalStatus = ProposalStatus.DRAFT
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    resolved_at: Optional[datetime] = None
    applied_at: Optional[datetime] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "agent_id": self.agent_id,
            "rationale": self.rationale,
            "status": self.status.value,
            "validation_passed": self.validation_passed,
            "safety_status": self.safety_status,
            "validation_errors": self.validation_errors,
            "validation_warnings": self.validation_warnings,
            "deltas": [
                {
                    "path": d.path,
                    "old_value": d.old_value,
                    "new_value": d.new_value,
                    "impact_level": d.impact_level,
                }
                for d in self.deltas
            ],
            "created_at": self.created_at.isoformat(),
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "applied_at": self.applied_at.isoformat() if self.applied_at else None,
        }


class ProposalEngine:
    """
    Generates and processes configuration proposals safely.
    """
    def __init__(self, config_loader: Optional[ConfigLoader] = None, validator: Optional[ConfigValidator] = None):
        self.loader = config_loader or ConfigLoader()
        self.validator = validator or ConfigValidator()
        self._proposals: Dict[str, ConfigurationProposal] = {}

    def create_proposal(
        self,
        agent_id: str,
        rationale: str,
        modifications: Dict[str, Any],
        base_profile: Optional[str] = None,
    ) -> ConfigurationProposal:
        """
        Creates a new proposal by merging modifications over active or specified profile configuration.
        Computes deep diff and runs validation.
        """
        # 1. Load baseline
        current_cfg, _ = self.loader.load(profile=base_profile)
        current_raw = current_cfg.to_dict()
        proposed_raw = copy.deepcopy(current_raw)

        # 2. Deep update proposed dictionary with modifications
        self._deep_update(proposed_raw, modifications)

        # 3. Compute deltas
        deltas = self._compute_deltas(current_raw, proposed_raw)

        proposal_id = f"prop_{uuid.uuid4().hex[:8]}"

        # 4. Validate proposed configuration against schemas and invariants
        try:
            proposed_obj = self.loader._build_config_instance(proposed_raw)
            val_report = self.validator.validate(proposed_obj)
            val_passed = val_report.is_valid
            val_errors = val_report.errors
            val_warnings = val_report.warnings
            safety_status = val_report.safety_status
            status = ProposalStatus.VALID if val_passed else ProposalStatus.INVALID
        except Exception as e:
            val_passed = False
            val_errors = [f"Failed to instantiate configuration: {str(e)}"]
            val_warnings = []
            safety_status = "ERROR"
            status = ProposalStatus.INVALID

        proposal = ConfigurationProposal(
            proposal_id=proposal_id,
            agent_id=agent_id,
            rationale=rationale,
            current_config=current_raw,
            proposed_config=proposed_raw,
            deltas=deltas,
            validation_passed=val_passed,
            validation_errors=val_errors,
            validation_warnings=val_warnings,
            safety_status=safety_status,
            status=status,
        )

        self._proposals[proposal_id] = proposal
        return proposal

    def approve_proposal(self, proposal_id: str) -> ConfigurationProposal:
        """Human operator approves a valid proposal."""
        prop = self._proposals.get(proposal_id)
        if not prop:
            raise KeyError(f"Proposal {proposal_id} not found")
        if not prop.validation_passed:
            raise ValueError(f"Cannot approve invalid proposal. Errors: {prop.validation_errors}")
        prop.status = ProposalStatus.APPROVED
        prop.resolved_at = datetime.now(timezone.utc)
        return prop

    def reject_proposal(self, proposal_id: str, reason: str = "Operator rejected") -> ConfigurationProposal:
        """Operator rejects proposal."""
        prop = self._proposals.get(proposal_id)
        if not prop:
            raise KeyError(f"Proposal {proposal_id} not found")
        prop.status = ProposalStatus.REJECTED
        prop.resolved_at = datetime.now(timezone.utc)
        return prop

    def apply_proposal(self, proposal_id: str, target_file_path: Optional[str] = None) -> Dict[str, Any]:
        """
        Applies an approved proposal by writing the updated configuration
        to a specified user config path without mutating source templates.
        """
        prop = self._proposals.get(proposal_id)
        if not prop:
            raise KeyError(f"Proposal {proposal_id} not found")
        if prop.status != ProposalStatus.APPROVED and not prop.validation_passed:
            raise ValueError(f"Proposal {proposal_id} must be valid or approved before applying.")

        import yaml
        dest = target_file_path or "cuanimus.user.yaml"
        with open(dest, "w") as f:
            yaml.dump(prop.proposed_config, f, default_flow_style=False, sort_keys=False)

        prop.status = ProposalStatus.APPLIED
        prop.applied_at = datetime.now(timezone.utc)
        return {
            "proposal_id": proposal_id,
            "status": "APPLIED",
            "destination_file": dest,
            "applied_at": prop.applied_at.isoformat(),
        }

    def get_proposal(self, proposal_id: str) -> Optional[ConfigurationProposal]:
        return self._proposals.get(proposal_id)

    @staticmethod
    def _deep_update(source: Dict[str, Any], overrides: Dict[str, Any]) -> None:
        """Recursively update nested dictionary."""
        for k, v in overrides.items():
            if isinstance(v, dict) and k in source and isinstance(source[k], dict):
                ProposalEngine._deep_update(source[k], v)
            else:
                source[k] = v

    @classmethod
    def _compute_deltas(
        cls, current: Dict[str, Any], proposed: Dict[str, Any], prefix: str = ""
    ) -> List[ConfigDelta]:
        """Traverses two dictionary trees and generates list of field diffs."""
        deltas: List[ConfigDelta] = []
        all_keys = set(current.keys()) | set(proposed.keys())

        for key in sorted(all_keys):
            cur_path = f"{prefix}.{key}" if prefix else key
            old_val = current.get(key)
            new_val = proposed.get(key)

            if isinstance(old_val, dict) and isinstance(new_val, dict):
                deltas.extend(cls._compute_deltas(old_val, new_val, cur_path))
            elif old_val != new_val:
                impact = cls._classify_impact(cur_path, old_val, new_val)
                deltas.append(ConfigDelta(
                    path=cur_path,
                    old_value=old_val,
                    new_value=new_val,
                    impact_level=impact,
                ))

        return deltas

    @staticmethod
    def _classify_impact(path: str, old_val: Any, new_val: Any) -> str:
        """Determines the risk classification of the changed parameter."""
        critical_keywords = ["live_trading", "stop_loss", "leverage", "secret", "key", "dry_run"]
        for kw in critical_keywords:
            if kw in path.lower():
                return "CRITICAL"
        notice_keywords = ["risk", "capital", "cooldown", "drawdown", "stake"]
        for kw in notice_keywords:
            if kw in path.lower():
                return "NOTICE"
        return "SAFE"
